spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.216.111:3306/hotel2
      username: root
      password: Zmj001015.
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.blog.sys.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8081
logging:
  level:
    com.ccu.server.dao: debug
